const types = {
    SET_ACTIVE_ID: "SET_ACTIVE_ID",
    SET_LAST_CANDLE_ID: "SET_LAST_CANDLE_ID",
    SET_PATTERN_LENGTH: "SET_PATTERN_LENGTH",
    SET_PATTERN: "SET_PATTERN",
    ADD_VALUE_TO_PATTERN: "ADD_VALUE_TO_PATTERN",
    ADD_CANDLE_VALUE: "ADD_CANDLE_VALUE",
};

export default types;
