const types = {
    SET_WS: "SET_WS",
    SET_TIME: "SET_TIME",
    SET_SSID: "SET_SSID",
    SET_PROFILE: "SET_PROFILE",
    SET_DEMO_BALANCE_ID: "SET_DEMO_BALANCE_ID",
    SET_REAL_BALANCE_ID: "SET_REAL_BALANCE_ID",
    SET_CONNECTION_STATE: "SET_CONNECTION_STATE",
    SET_TURBO_ACTIVES: "SET_TURBO_ACTIVES",
    SET_BINARY_ACTIVES: "SET_BINARY_ACTIVES",
};

export default types;
